name: Deploy

on: 
  push:
    branches: "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy to server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ HOST.HOST }}
        USERNAME: ${{ HOST.USERNAME }}
        PORT: ${{ HOST.PORT }}
        KEY: ${{ HOST.SSHKEY }}
      with:
        source: "."
        target: "/var/www/app"

    - name: build app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: "cd /var/www/app && yarn && yarn build"
        
    - name: move app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: "mv -f /var/www/app/build/* /var/www/curswork"

    - name: remove garbadge
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: "rm -f /var/www/app/*"
